# Generated by Django 5.1.6 on 2025-02-26 15:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('1', 'Moniuszki'), ('2', 'Laska')], max_length=100)),
                ('table', models.CharField(choices=[('1', 'Snooker nr.1'), ('2', 'Snooker nr.2'), ('3', 'Pool nr.1'), ('4', 'Pool nr.2')], max_length=100)),
                ('bookingtype', models.CharField(choices=[('1', 'Liga'), ('2', 'Turniej'), ('3', 'Trening'), ('4', 'Moge z kims ragrac'), ('5', 'Rezerwuje dla 2 osob'), ('6', 'Szkolka Dorosli'), ('7', 'Szkolka Dzieci'), ('8', 'Brak mozliwosci')], default='Liga', max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(default='07:00:00')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('1', 'Moniuszki'), ('2', 'Laska')], default='Moniuszki', max_length=100)),
                ('table', models.CharField(choices=[('1', 'Snooker nr.1'), ('2', 'Snooker nr.2'), ('3', 'Pool nr.1'), ('4', 'Pool nr.2')], default='Sonnker nr.1', max_length=100)),
                ('bookingtype', models.CharField(choices=[('1', 'Liga'), ('2', 'Turniej'), ('3', 'Trening'), ('4', 'Moge z kims ragrac'), ('5', 'Rezerwuje dla 2 osob'), ('6', 'Szkolka Dorosli'), ('7', 'Szkolka Dzieci'), ('8', 'Brak mozliwosci')], default='Liga', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/profile_pics/default.png', upload_to='profile_pics')),
                ('user_code', models.CharField(max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
