# Generated by Django 5.1.6 on 2025-02-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lutnia_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
