# Generated by Django 5.1.6 on 2025-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutnia_app', '0004_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='table',
            field=models.CharField(choices=[('1', 'Snooker nr.1'), ('2', 'Snooker nr.2'), ('3', 'Pool nr.1'), ('4', 'Pool nr.2'), ('5', 'Snooker nr.3'), ('6', 'Snooker nr.4'), ('7', 'Snooker nr.5')], default='Sonnker nr.1', max_length=100),
        ),
    ]
