# Generated by Django 5.1.6 on 2025-03-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutnia_app', '0005_alter_event_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
