# Generated by Django 5.1.6 on 2025-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutnia_app', '0006_alter_profile_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
