# Generated by Django 5.1.6 on 2025-03-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutnia_app', '0007_alter_profile_image_alter_profile_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
